name: Trigger URL Every Night

on:
  schedule:
    - cron: '15 14 * * *'  # Every day at 2:15 PM UTC (which is 8:00 PM GMT+5:45)

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Make HTTP Request
        run: |
          curl -X GET "https://nnnn-27u0.onrender.com/cdn/shorts/"
